name: ECR
on:
  push:
    branches:
    - main
    paths:
    - 'apichanges/**'
    - 'assets/**'
    - 'templates/**'
    - 'tools/**'
    - 'justfile'
    - 'Dockerfile'
    - 'requirements.txt'
    - '.github/workflows/ecr.yaml'

# AWS OIDC 
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: apichanges
      AWS_REGION: us-west-2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::347516098724:role/github-actions-role
        role-session-name: github-action-session
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag and push to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
